import {
  MdPause,
  MdPlayArrow,
  MdSkipNext,
  MdSkipPrevious,
  MdVolumeOff,
  MdVolumeUp,
  MdHome,
  MdSearch,
  MdSettings,
  MdShuffleOn,
  MdShuffle,
  MdDarkMode,
  MdLightMode,
  MdArrowBack,
  MdOutlineArrowBackIos,
  MdRepeat,
  MdRepeatOn,
  MdAlbum,
  MdAudiotrack,
  MdOutlineLineWeight,
  MdPerson,
} from 'react-icons/md';
import Play from './play/index';
import PlayPause from './play-pause/index';

export {
  Play,
  PlayPause,
  MdSearch as Search,
  MdArrowBack as Back,
  //MdOutlineArrowBackIos as Back,
  MdPause as Pause,
  MdSkipNext as SkipNext,
  MdSkipPrevious as SkipPrevious,
  MdVolumeOff as VolumeOff,
  MdVolumeUp as VolumeUp,
  MdRepeat as Repeat,
  MdRepeat as RepeatOff,
  MdRepeatOn as RepeatOn,
  MdHome as Home,
  MdSettings as Settings,
  MdShuffleOn as ShuffleOn,
  MdShuffle as ShuffleOff,
  MdShuffle as Shuffle,
  MdDarkMode as DarkMode,
  MdLightMode as LightMode,
  MdAlbum as Album,
  MdAudiotrack as Track,
  MdOutlineLineWeight as ListAll,
  MdPerson as Artist,
};
