import {
  MdPause,
  MdPlayArrow,
  MdSkipNext,
  MdSkipPrevious,
  MdVolumeOff,
  MdVolumeUp,
  MdHome,
  MdSettings,
  MdShuffleOn,
  MdShuffle,
  MdDarkMode,
  MdLightMode,
  MdOutlineArrowBackIos,
  MdRepeat,
  MdRepeatOn,
} from 'react-icons/md';
import Play from './play/index';
import PlayPause from './play-pause/index';

export {
  Play,
  PlayPause,
  MdOutlineArrowBackIos as Back,
  MdPause as Pause,
  MdSkipNext as SkipNext,
  MdSkipPrevious as SkipPrevious,
  MdVolumeOff as VolumeOff,
  MdVolumeUp as VolumeUp,
  MdRepeat as Repeat,
  MdRepeat as RepeatOff,
  MdRepeatOn as RepeatOn,
  MdHome as Home,
  MdSettings as Settings,
  MdShuffleOn as ShuffleOn,
  MdShuffle as ShuffleOff,
  MdShuffle as Shuffle,
  MdDarkMode as DarkMode,
  MdLightMode as LightMode,
};
